"""create_or_update_soccer_tables

Revision ID: 3fb80755709e
Revises: 5dbcf2951d5b
Create Date: 2026-01-27 16:21:44.752828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3fb80755709e'
down_revision = '5dbcf2951d5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('langchain_documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('langchain_documents',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('langchain_documents_pkey'))
    )
    # ### end Alembic commands ###
