"""create_or_update_soccer_tables

Revision ID: e989a40316ad
Revises: 9801d63cd36a
Create Date: 2026-01-27 16:16:41.939437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e989a40316ad'
down_revision = '9801d63cd36a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('langchain_documents')
    op.drop_constraint(op.f('stadium_hometeam_numeric_id_fkey'), 'stadium', type_='foreignkey')
    op.drop_constraint(op.f('stadium_hometeam_id_fkey'), 'stadium', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('stadium_hometeam_id_fkey'), 'stadium', 'team', ['hometeam_id'], ['team_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('stadium_hometeam_numeric_id_fkey'), 'stadium', 'team', ['hometeam_numeric_id'], ['id'], ondelete='SET NULL')
    op.create_table('langchain_documents',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('langchain_documents_pkey'))
    )
    # ### end Alembic commands ###
