"""create_or_update_soccer_tables

Revision ID: e5a59b400ba0
Revises: 
Create Date: 2026-01-27 15:49:26.885900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5a59b400ba0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('langchain_documents')
    
    # 먼저 team 테이블에 team_id 컬럼 추가 (외래키 생성 전에 필요)
    op.add_column('team', sa.Column('team_id', sa.String(length=10), nullable=True))  # 일단 nullable로 추가
    op.create_index(op.f('ix_team_team_id'), 'team', ['team_id'], unique=True)
    
    # 이제 player 테이블 변경
    op.add_column('player', sa.Column('team_numeric_id', sa.String(length=20), nullable=True))
    op.alter_column('player', 'player_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('player', 'e_player_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('player', 'nickname',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('player', 'nation',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_player_team_id'), 'player', ['team_id'], unique=False)
    op.create_index(op.f('ix_player_team_numeric_id'), 'player', ['team_numeric_id'], unique=False)
    op.drop_constraint(op.f('player_team_id_fkey'), 'player', type_='foreignkey')
    op.create_foreign_key(None, 'player', 'team', ['team_numeric_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'player', 'team', ['team_id'], ['team_id'], ondelete='SET NULL')
    op.add_column('schedule', sa.Column('stadium_numeric_id', sa.String(length=20), nullable=True))
    op.add_column('schedule', sa.Column('hometeam_numeric_id', sa.String(length=20), nullable=True))
    op.add_column('schedule', sa.Column('awayteam_numeric_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_schedule_awayteam_id'), 'schedule', ['awayteam_id'], unique=False)
    op.create_index(op.f('ix_schedule_awayteam_numeric_id'), 'schedule', ['awayteam_numeric_id'], unique=False)
    op.create_index(op.f('ix_schedule_hometeam_id'), 'schedule', ['hometeam_id'], unique=False)
    op.create_index(op.f('ix_schedule_hometeam_numeric_id'), 'schedule', ['hometeam_numeric_id'], unique=False)
    op.create_index(op.f('ix_schedule_stadium_numeric_id'), 'schedule', ['stadium_numeric_id'], unique=False)
    op.drop_constraint(op.f('schedule_awayteam_id_fkey'), 'schedule', type_='foreignkey')
    op.drop_constraint(op.f('schedule_hometeam_id_fkey'), 'schedule', type_='foreignkey')
    op.drop_constraint(op.f('schedule_stadium_id_fkey'), 'schedule', type_='foreignkey')
    op.create_foreign_key(None, 'schedule', 'stadium', ['stadium_id'], ['stadium_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'schedule', 'team', ['awayteam_numeric_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'schedule', 'team', ['hometeam_numeric_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'schedule', 'stadium', ['stadium_numeric_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'schedule', 'team', ['awayteam_id'], ['team_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'schedule', 'team', ['hometeam_id'], ['team_id'], ondelete='SET NULL')
    op.add_column('stadium', sa.Column('hometeam_numeric_id', sa.String(length=20), nullable=True))
    op.alter_column('stadium', 'stadium_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('stadium', 'address',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('stadium', 'tel',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.create_index(op.f('ix_stadium_hometeam_id'), 'stadium', ['hometeam_id'], unique=False)
    op.create_index(op.f('ix_stadium_hometeam_numeric_id'), 'stadium', ['hometeam_numeric_id'], unique=False)
    op.drop_constraint(op.f('stadium_hometeam_id_fkey'), 'stadium', type_='foreignkey')
    op.create_foreign_key(None, 'stadium', 'team', ['hometeam_numeric_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'stadium', 'team', ['hometeam_id'], ['team_id'], ondelete='SET NULL')
    # team_id는 이미 위에서 추가됨
    op.add_column('team', sa.Column('stadium_numeric_id', sa.String(length=20), nullable=True))
    op.alter_column('team', 'region_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('team', 'team_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('team', 'e_team_name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('team', 'address',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('team', 'tel',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('team', 'fax',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('team', 'homepage',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('team', 'owner',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    # team_code를 team_id로 복사 (team_code 삭제 전에 수행)
    try:
        op.execute("""
            UPDATE team 
            SET team_id = team_code 
            WHERE team_id IS NULL AND team_code IS NOT NULL
        """)
    except Exception:
        # team_code가 없는 경우 무시 (이미 삭제되었거나 처음부터 없었을 수 있음)
        pass
    
    # team_id가 여전히 NULL인 경우 기본값 설정 (임시)
    try:
        op.execute("""
            UPDATE team 
            SET team_id = 'TEMP' || id 
            WHERE team_id IS NULL
        """)
    except Exception:
        pass
    
    # 이제 NOT NULL로 변경 (team_code 삭제 전에 수행)
    try:
        op.alter_column('team', 'team_id', nullable=False)
    except Exception as e:
        # NOT NULL 변경 실패 시 경고만 출력하고 계속 진행
        print(f"⚠️ team_id를 NOT NULL로 변경 실패 (기존 NULL 값이 있을 수 있음): {e}")
    
    op.drop_index(op.f('ix_team_team_code'), table_name='team')
    op.create_index(op.f('ix_team_stadium_id'), 'team', ['stadium_id'], unique=False)
    op.create_index(op.f('ix_team_stadium_numeric_id'), 'team', ['stadium_numeric_id'], unique=False)
    # team_id 인덱스는 이미 위에서 생성됨
    op.drop_constraint(op.f('team_stadium_id_fkey'), 'team', type_='foreignkey')
    op.create_foreign_key(None, 'team', 'stadium', ['stadium_numeric_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'team', 'stadium', ['stadium_id'], ['stadium_id'], ondelete='SET NULL')
    op.drop_column('team', 'team_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('team_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.create_foreign_key(op.f('team_stadium_id_fkey'), 'team', 'stadium', ['stadium_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_team_team_id'), table_name='team')
    op.drop_index(op.f('ix_team_stadium_numeric_id'), table_name='team')
    op.drop_index(op.f('ix_team_stadium_id'), table_name='team')
    op.create_index(op.f('ix_team_team_code'), 'team', ['team_code'], unique=True)
    op.alter_column('team', 'owner',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('team', 'homepage',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('team', 'fax',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('team', 'tel',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('team', 'address',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('team', 'e_team_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    op.alter_column('team', 'team_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('team', 'region_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('team', 'stadium_numeric_id')
    op.drop_column('team', 'team_id')
    op.drop_constraint(None, 'stadium', type_='foreignkey')
    op.drop_constraint(None, 'stadium', type_='foreignkey')
    op.create_foreign_key(op.f('stadium_hometeam_id_fkey'), 'stadium', 'team', ['hometeam_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_stadium_hometeam_numeric_id'), table_name='stadium')
    op.drop_index(op.f('ix_stadium_hometeam_id'), table_name='stadium')
    op.alter_column('stadium', 'tel',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('stadium', 'address',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('stadium', 'stadium_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('stadium', 'hometeam_numeric_id')
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.create_foreign_key(op.f('schedule_stadium_id_fkey'), 'schedule', 'stadium', ['stadium_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('schedule_hometeam_id_fkey'), 'schedule', 'team', ['hometeam_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('schedule_awayteam_id_fkey'), 'schedule', 'team', ['awayteam_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_schedule_stadium_numeric_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_hometeam_numeric_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_hometeam_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_awayteam_numeric_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_awayteam_id'), table_name='schedule')
    op.drop_column('schedule', 'awayteam_numeric_id')
    op.drop_column('schedule', 'hometeam_numeric_id')
    op.drop_column('schedule', 'stadium_numeric_id')
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.create_foreign_key(op.f('player_team_id_fkey'), 'player', 'team', ['team_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_player_team_numeric_id'), table_name='player')
    op.drop_index(op.f('ix_player_team_id'), table_name='player')
    op.alter_column('player', 'nation',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('player', 'nickname',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('player', 'e_player_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('player', 'player_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('player', 'team_numeric_id')
    op.create_table('langchain_documents',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('langchain_documents_pkey'))
    )
    # ### end Alembic commands ###
