"""create_or_update_soccer_tables

Revision ID: deccd1ef9fac
Revises: e5a59b400ba0
Create Date: 2026-01-27 15:53:15.422474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deccd1ef9fac'
down_revision = 'e5a59b400ba0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
