"""create_or_update_soccer_tables

Revision ID: c4aa048de1f3
Revises: 375e8a0d9671
Create Date: 2026-01-27 16:08:04.833151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4aa048de1f3'
down_revision = '375e8a0d9671'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('langchain_documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('langchain_documents',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('langchain_documents_pkey'))
    )
    # ### end Alembic commands ###
